#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/yabai
ln -s $DOTFILES/yabai $HOME/.config/yabai

rm -rf $HOME/.config/skhd
ln -s $DOTFILES/skhd $HOME/.config/skhd

ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

ln -sf $DOTFILES/git/gitignore_global $HOME/.gitignore_global

mkdir -p $HOME/.local/bin

touch $HOME/.hushlogin

if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
